export const upload: IComponents = {
  root: {
    id: 'root',
    parent: 'root',
    type: 'Box',
    children: ['comp-LM5U5PDX6PJHF'],
    props: {
      colorScheme: 'green',
    },
  },
  'comp-LM5U5PDX6PJHF': {
    id: 'comp-LM5U5PDX6PJHF',
    props: {
      spacing: 2,
      minW: '500px',
      minH: '50vh',
    },
    children: [
      'comp-LM5U7YHVG6AI4',
      'comp-LM5VAI5ZMVK4K',
      'comp-LM5VEIURN7FGK',
      'comp-LM5VGAX5XVN9D',
    ],
    type: 'Stack',
    parent: 'root',
    rootParentType: 'Stack',
  },
  'comp-LM5U7YHVG6AI4': {
    id: 'comp-LM5U7YHVG6AI4',
    props: {
      rounded: 'lg',
      w: 'full',
      minH: '30%',
      bgColor: 'gray.200',
      display: 'flex',
      flexDirection: 'column',
      p: '6',
    },
    children: ['comp-LM5V6K64FB8HE', 'comp-LM5V7HZZ0S9H4'],
    type: 'Box',
    parent: 'comp-LM5U5PDX6PJHF',
    rootParentType: 'Box',
  },
  'comp-LM5V6K64FB8HE': {
    id: 'comp-LM5V6K64FB8HE',
    props: {
      children: 'Upload',
      textAlign: 'center',
      fontWeight: 'bold',
    },
    children: [],
    type: 'Text',
    parent: 'comp-LM5U7YHVG6AI4',
    rootParentType: 'Text',
  },
  'comp-LM5V7HZZ0S9H4': {
    id: 'comp-LM5V7HZZ0S9H4',
    props: {
      children: 'Upload or drag and drop your files here',
      textAlign: 'center',
      color: 'gray.500',
      fontSize: 'sm',
    },
    children: [],
    type: 'Text',
    parent: 'comp-LM5U7YHVG6AI4',
    rootParentType: 'Text',
  },
  'comp-LM5VAI5ZMVK4K': {
    id: 'comp-LM5VAI5ZMVK4K',
    props: {
      size: '48px',
      value: 60,
      min: 0,
      max: 100,
      alignSelf: 'center',
      isIndeterminate: false,
      color: 'green',
    },
    children: [],
    type: 'CircularProgress',
    parent: 'comp-LM5U5PDX6PJHF',
    rootParentType: 'CircularProgress',
  },
  'comp-LM5VEIURN7FGK': {
    id: 'comp-LM5VEIURN7FGK',
    props: {
      children: '60%',
      textAlign: 'center',
      color: 'gray.500',
      fontSize: 'sm',
    },
    children: [],
    type: 'Text',
    parent: 'comp-LM5U5PDX6PJHF',
    rootParentType: 'Text',
  },
  'comp-LM5VGAX5XVN9D': {
    id: 'comp-LM5VGAX5XVN9D',
    props: {
      justifyContent: 'flex-end',
      gap: '4',
      colorScheme: 'green',
    },
    children: ['comp-LM5VH0AB85AW0', 'comp-LM5VHQX5EPPVF'],
    type: 'Flex',
    parent: 'comp-LM5U5PDX6PJHF',
    rootParentType: 'Flex',
  },
  'comp-LM5VH0AB85AW0': {
    id: 'comp-LM5VH0AB85AW0',
    props: {
      children: 'Cancel',
      variant: 'outline',
      size: 'sm',
      colorScheme: 'green',
    },
    children: [],
    type: 'Button',
    parent: 'comp-LM5VGAX5XVN9D',
    rootParentType: 'Button',
  },
  'comp-LM5VHQX5EPPVF': {
    id: 'comp-LM5VHQX5EPPVF',
    props: {
      children: 'Upload',
      variant: 'solid',
      size: 'sm',
      colorScheme: 'green',
    },
    children: [],
    type: 'Button',
    parent: 'comp-LM5VGAX5XVN9D',
    rootParentType: 'Button',
  },
}
